# Definitions for jobs that run periodically.  For details on the format, see
# ``https://github.com/mozilla-releng/fxci-config/blob/main/build-decision/src/build_decision/cron/schema.yml``.
# For documentation, see `taskcluster/docs/cron.rst`.
---
jobs:
    - name: run-integration-tests
      job:
          type: decision-task
          target-tasks-method: integration
      when: []  # never (hook only)
