---
image:
  publisher: MicrosoftWindowsServer
  offer: WindowsServer
  sku: 2022-datacenter-azure-edition
  version: latest
sharedimage:
  gallery_name: "trusted_win2022_64_2009"
  image_name: "trusted_win2022_64_2009"
  image_version: "default"
azure:
  managed_image_resource_group_name: "default"
  managed_image_storage_account_type: "default"
vm:
  clone_mozilla_unified: "default"
  puppet_version: "default"
  git_version: "default"
  openvox_version: "default"
  size: Standard_F32s_v2
  tags:
    base_image: win2022642009azure
    worker_pool_id: trusted-win2022-64-2009
    sourceOrganization: "default"
    sourceRepository: "default"
    sourceBranch: "default"
    deploymentId: "default"
    managed_by: "default"
tests:
  - microsoft_tools_builder.tests.ps1
  - disable_services_builder.tests.ps1
  - error_reporting.tests.ps1
  - suppress_dialog_boxes.tests.ps1
  - files_system_management.tests.ps1
  - firewall.tests.ps1
  - network.tests.ps1
  - ntp.tests.ps1
  - power_management.tests.ps1
  - scheduled_tasks.tests.ps1
  - azure_vm_agent.tests.ps1
  - logging.tests.ps1
  - common_tools_builder.tests.ps1
  - google_auth.tests.ps1
  - git.tests.ps1
  - mozilla_build_builder.tests.ps1
  - windows_worker_runner.tests.ps1