---
image:
  publisher: MicrosoftWindowsDesktop
  offer: windows11preview-arm64
  sku: win11-24h2-ent
  version: latest
sharedimage:
  gallery_name: "win11_a64_24h2_tester"
  image_name: "win11_a64_24h2_tester"
  image_version: "default"
azure:
  managed_image_resource_group_name: "default"
  managed_image_storage_account_type: "default"
vm:
  puppet_version: "default"
  git_version: "default"
  openvox_version: "default"
  size: Standard_E8pds_v5
  tags:
    base_image: win11a6424h2azuretester
    worker_pool_id: win11-a64-24h2-tester
    sourceOrganization: "default"
    sourceRepository: "default"
    sourceBranch: "default"
    deploymentId: "default"
    managed_by: "default"
tests:
  - microsoft_tools_tester_a64.tests.ps1
  - error_reporting.tests.ps1
  - suppress_dialog_boxes.tests.ps1
  - files_system_management.tests.ps1
  - firewall.tests.ps1
  - network.tests.ps1
  - ntp.tests.ps1
  - power_management.tests.ps1
  - scheduled_tasks.tests.ps1
  - azure_vm_agent.tests.ps1
  - logging.tests.ps1
  - common_tools_tester.tests.ps1
  - git.tests.ps1
  - mozilla_build_tester.tests.ps1
  - windows_worker_runner.tests.ps1
