---
azure:
  managed_image_resource_group_name: rg-packer-worker-images
  managed_image_storage_account_type: Standard_LRS
sharedimage:
  image_version: 99.86.43
vm:
  puppet_version: 8.10.0
  git_version: 2.49.0
  tags:
    sourceOrganization: mozilla-platform-ops
    sourceRepository: ronin_puppet
    sourceBranch: windows
    managed_by: packer
    deploymentId: "389b2fc"
Images:
  win10-64-2009-alpha
  win11-64-2009-alpha
  win2022-64-2009-alpha