run-name: TCEng GCP - ${{ github.event.inputs.config }}
name: TCEng GCP

on:
  workflow_dispatch:
    inputs:
      config:
        type: string
        required: true
        description: YAML basename from config/ (without .yaml)
      TASKCLUSTER_REF:
        type: string
        description: Git reference (branch, tag, or commit) to use
        default: main

permissions:
  id-token: write
  contents: read

env:
  CONFIG: ${{ inputs.config }}

jobs:
  check-access:
    name: "Verify User Access"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Validate image config
        shell: pwsh
        run: ./ci/validate-image-config.ps1 -Family tceng

      - name: Load Authorized Users and Check Access
        shell: pwsh
        run: ./ci/check-authorized-user.ps1 -IncludeTCEng

  setproject:
    needs: check-access
    name: "Get Project ID & ImageName from Config"
    runs-on: ubuntu-latest
    outputs:
      IMAGENAME: ${{ steps.set-matrix.outputs.IMAGENAME }}
      PROJECT:   ${{ steps.set-matrix.outputs.PROJECT }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Validate image config
        shell: pwsh
        run: ./ci/validate-image-config.ps1 -Family tceng
      - id: set-matrix
        shell: pwsh
        run: |
          Import-Module "${{ github.workspace }}/bin/WorkerImages/WorkerImages.psm1"
          Set-GCPWorkerImageMetadata    -Key $env:CONFIG -Team 'tceng'

  packer:
    needs: setproject
    name: "GCP ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - name: Validate image config
        shell: pwsh
        run: ./ci/validate-image-config.ps1 -Family tceng

      - uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093'
        id: auth
        with:
          workload_identity_provider: "projects/324168772199/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "deploy-prod@${{ needs.setproject.outputs.PROJECT }}.iam.gserviceaccount.com"

      - name: Run Packer
        uses: ./.github/actions/packer-build
        with:
          builder: gcp-tceng
          config: ${{ inputs.config }}
          taskcluster-ref: ${{ inputs.TASKCLUSTER_REF }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
