run-name: GCP Production - ${{ github.event.inputs.config }}
name: FXCI - GCP Production

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - gw-fxci-gcp-l1-2404-gui-alpha
        - gw-fxci-gcp-l1-2404-headless-alpha
        - gw-fxci-gcp-l1-2404-arm64-headless-alpha
        - trusted-gw-fxci-gcp-l3-2404-headless-alpha

permissions:
  id-token: write
  contents: read

jobs:
  check-access:
    name: "Verify User Access"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load Authorized Users and Check Access
        shell: pwsh
        run: |
          $AUTHORIZED_USERS=$(Get-Content .github/relsre.json | Convertfrom-Json)
          if ($authorized_users -contains "${{ github.actor }}") {
            Write-host "User ${{ github.actor }} is authorized."
          }
          else {
            Write-Host "User ${{ github.actor }} is unauthorized."
            exit 1
          }
  setproject:
    needs: check-access
    name: "Get Project ID & ImageName from Config"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        shell: pwsh
        run: |
          Import-Module ${{ github.workspace }}\bin\WorkerImages\WorkerImages.psm1
          Set-GCPWorkerImageName -Key '${{ github.event.inputs.config }}'
          Set-GCPWorkerImageProject -Key '${{ github.event.inputs.config }}'
    outputs:
      IMAGENAME: ${{ steps.set-matrix.outputs.IMAGENAME }}
      PROJECT: ${{ steps.set-matrix.outputs.PROJECT }}
  prodimage:
    needs: setproject
    name: "GCP ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          workload_identity_provider: "projects/324168772199/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "deploy-prod@${{ needs.setproject.outputs.PROJECT }}.iam.gserviceaccount.com"
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Build Production Image'
        shell: pwsh
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          $ProdImageName = -join(('${{ needs.setproject.outputs.IMAGENAME }}' -Replace "alpha"),$date)
          $exists = gcloud compute images describe $ProdImageName
          if ($exists) {
            gcloud compute images delete $ProdImageName --quiet
          }
          Write-Output "Creating image $ProdImageName"
          gcloud compute images create $ProdImageName `
          --source-image ${{ needs.setproject.outputs.IMAGENAME }} `
          --source-image-project ${{ needs.setproject.outputs.PROJECT }} `
          --force 