run-name: Wiz Scan - ${{ github.event.inputs.config }}
name: FXCI - Wiz Scan

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - gw-fxci-gcp-l1-2404-gui-alpha
        - gw-fxci-gcp-l1-2404-headless-alpha
        - gw-fxci-gcp-l1-2404-arm64-headless-alpha

jobs:
  check-access:
    name: "Verify User Access"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load Authorized Users and Check Access
        shell: pwsh
        run: |
          $AUTHORIZED_USERS=$(Get-Content .github/relsre.json | Convertfrom-Json)
          if ($authorized_users -contains "${{ github.actor }}") {
            Write-host "User ${{ github.actor }} is authorized."
          }
          else {
            Write-Host "User ${{ github.actor }} is unauthorized."
            exit 1
          }
  setproject:
    needs: check-access
    name: "Get Project ID & ImageName from Config"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        shell: pwsh
        run: |
          Import-Module ${{ github.workspace }}\bin\WorkerImages\WorkerImages.psm1
          Set-GCPWorkerImageName -Key '${{ github.event.inputs.config }}'
          Set-GCPWorkerImageProject -Key '${{ github.event.inputs.config }}'
    outputs:
      IMAGENAME: ${{ steps.set-matrix.outputs.IMAGENAME }}
      PROJECT: ${{ steps.set-matrix.outputs.PROJECT }}
  wiz:
    needs: setproject
    name: "Wiz scan ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli
      - name: Authenticate to Wiz
        run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Run wiz-cli scan
        run: |
          ./wizcli vm-image scan \
          --id ${{ needs.setproject.outputs.IMAGENAME }} \
          --region us-west1 \
          --subscriptionId ${{ needs.setproject.outputs.PROJECT }} \
          --secrets \
          --show-vulnerability-details \
          --policy-hits-only