name: FXCI - Azure Prod Parallel Images
run-name: Azure Production Parallel - ${{ github.sha }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  prepare-matrix:
    name: Prepare Production Image Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      os_integration_matrix: ${{ steps.set-matrix.outputs.os_integration_matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Install PowerShell-YAML module
        shell: pwsh
        run: |
          & "${{ github.workspace }}/ci/install-powershell-yaml.ps1"

      - id: set-matrix
        name: Extract Azure production configs
        shell: pwsh
        run: |
          & "${{ github.workspace }}/ci/get-azure-production-parallel-matrix.ps1"

  packer:
    needs: [prepare-matrix]
    name: "Build ${{ matrix.config }}"
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    uses: ./.github/workflows/build-azure-image.yml
    with:
      config: ${{ matrix.config }}
      trusted: ${{ startsWith(matrix.config, 'trusted-') }}
    secrets:
      client-id: ${{ secrets[matrix.client_id_secret] }}
      application-id: ${{ secrets[matrix.application_id_secret] }}
      subscription-id: ${{ secrets[matrix.subscription_id_secret] }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  sbom:
    if: ${{ always() }}
    needs: [prepare-matrix, packer]
    permissions:
      actions: read
      contents: write
    uses: ./.github/workflows/upload-release-notes.yml

  os-integration:
    needs: [prepare-matrix, packer]
    name: "OS Integration Tests - ${{ matrix.config }}"
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.os_integration_matrix) }}
    uses: ./.github/workflows/os-integration.yml
    with:
      config: ${{ matrix.config }}
    secrets:
      TASKCLUSTER_OS_INT_CLIENT_ID: ${{ secrets.TASKCLUSTER_OS_INT_CLIENT_ID }}
      TASKCLUSTER_OS_INT_ACCESS_TOKEN: ${{ secrets.TASKCLUSTER_OS_INT_ACCESS_TOKEN }}
