run-name: FXCI Azure Trusted - ${{ github.event.inputs.config }}
name: FXCI - Azure - Trusted

on:
  workflow_dispatch:
    inputs:
      config:
        type: choice
        description: Choose which pool to build
        options:
        - trusted-win11-a64-25h2-builder
        - trusted-win2022-64-2009

permissions:
  id-token: write
  contents: read

jobs:
  check-access:
    name: "Verify User Access"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Load Authorized Users and Check Access
        shell: pwsh
        run: |
          $AUTHORIZED_USERS=$(Get-Content .github/relsre.json | Convertfrom-Json)
          if ($authorized_users -contains "${{ github.actor }}") {
            Write-host "User ${{ github.actor }} is authorized."
          }
          else {
            Write-Host "User ${{ github.actor }} is unauthorized."
            exit 1
          }
  packer:
    needs: check-access
    name: "Build ${{ github.event.inputs.config }}"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Azure Login
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_FXCI_TRUSTED }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_TRUSTED }}
          enable-AzPSSession: true
      - name: 'Run Packer'
        shell: pwsh
        run: |
          Import-Module .\bin\WorkerImages\WorkerImages.psm1
          $Vars = @{
            github_token = "${{ secrets.GITHUB_TOKEN }}"
            Key = '${{ github.event.inputs.config }}'
            Client_ID = "${{ secrets.AZURE_CLIENT_ID_FXCI_TRUSTED }}"
            oidc_request_url = $env:ACTIONS_ID_TOKEN_REQUEST_URL
            oidc_request_token = $env:ACTIONS_ID_TOKEN_REQUEST_TOKEN
            Subscription_ID = "${{ secrets.AZURE_SUBSCRIPTION_ID_TRUSTED }}"
            Tenant_ID = "${{ secrets.AZURE_TENANT_ID }}"
            Application_ID = "${{ secrets.AZURE_APPLICATION_ID_FXCI_TRUSTED }}"
          }
          New-AzSharedWorkerImage @Vars
          "sharedimageversion=$ENV:PKR_VAR_sharedimage_version" >> $env:GITHUB_ENV
      - name: Upload Release Notes Artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: release-notes-${{ github.event.inputs.config }}
          path: ${{ github.event.inputs.config }}-${{ env.sharedimageversion }}.md
          overwrite: true
          retention-days: 1
          if-no-files-found: error
  sbom:
    needs: packer
    permissions: write-all
    uses: ./.github/workflows/upload-release-notes.yml
    with:
      artifact_pattern: release-notes-${{ github.event.inputs.config }}
      commit_message: ${{ github.event.inputs.config }} - Release Notes
