run-name: FXCI - Azure - ${{ github.event.inputs.config }}
name: FXCI - Azure

on:
  workflow_dispatch:
    inputs:
      config:
        type: string
        required: true
        description: YAML basename from config/ (without .yaml)

permissions:
  id-token: write
  contents: read

jobs:
  region-check:
    uses: ./.github/workflows/check-azure-regions.yml

  packer:
    needs: [region-check]
    name: "Build ${{ github.event.inputs.config }}"
    uses: ./.github/workflows/build-azure-image.yml
    with:
      config: ${{ github.event.inputs.config }}
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID_FXCI }}
      application-id: ${{ secrets.AZURE_APPLICATION_ID_FXCI }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_UNTRUSTED }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  sbom:
    needs: packer
    permissions:
      actions: read
      contents: write
    uses: ./.github/workflows/upload-release-notes.yml
    with:
      artifact_pattern: release-notes-${{ github.event.inputs.config }}
      commit_message: ${{ github.event.inputs.config }} - Release Notes
  os-integration:
    needs: packer
    if: ${{ !startsWith(github.event.inputs.config, 'win20') }}
    name: "OS Integration Tests"
    uses: ./.github/workflows/os-integration.yml
    with:
      config: ${{ github.event.inputs.config }}
    secrets:
      TASKCLUSTER_OS_INT_CLIENT_ID: ${{ secrets.TASKCLUSTER_OS_INT_CLIENT_ID }}
      TASKCLUSTER_OS_INT_ACCESS_TOKEN: ${{ secrets.TASKCLUSTER_OS_INT_ACCESS_TOKEN }}
