run-name: FXCI Azure Trusted - ${{ github.event.inputs.config }}
name: FXCI - Azure - Trusted

on:
  workflow_dispatch:
    inputs:
      config:
        type: string
        required: true
        description: YAML basename from config/ (without .yaml)

permissions:
  id-token: write
  contents: read

jobs:
  packer:
    name: "Build ${{ github.event.inputs.config }}"
    uses: ./.github/workflows/build-azure-image.yml
    with:
      config: ${{ github.event.inputs.config }}
      trusted: true
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID_FXCI_TRUSTED }}
      application-id: ${{ secrets.AZURE_APPLICATION_ID_FXCI_TRUSTED }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_TRUSTED }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}

  sbom:
    needs: packer
    permissions:
      actions: read
      contents: write
    uses: ./.github/workflows/upload-release-notes.yml
    with:
      artifact_pattern: release-notes-${{ github.event.inputs.config }}
      commit_message: ${{ github.event.inputs.config }} - Release Notes
